### ISSUE TITLE
PLAYERS WEEKLY STATS/SCORING 

### ISSUE THREAD

**Issue by Natonic17** [mdryden/110yards#18]
Hi I have a little bit of a problem... I lost my weekly matchup because of about 2 points but 2 players on my team are short 6 points.. those players are Antoine Pruneau who had 6 tkls but only got 4 points and Jovon Santos-knox who had 3 tkls but only got points for 2 tkls ... I think you guys are doing a great job! And I love using your site ... I just hate to lose to the guy in first place because I'm short 2 points and I'm missing 6 ... if you could fix this asap that would be great! Thanks! And keep up the good work! 😊

**Comment by pudds** [comment]
Pruneau only had 4 tackles vs WPG this week, and Santos-Knox only had 2.  I think you are mixing up Defensive Tackles and Special Teams Tackles (Pruneau had 2 ST and Santos-Knox had 1).

None of the 3 scoring options reward special teams tackles, only defensive tackles.

**Comment by Natonic17** [comment]
Ok yes I am mixing up defensive tackles and special teams ... thanks for getting back to me so quickly... still sucks I lost my matchup for week 10 by 1 point lol ...
