### ISSUE TITLE
Points

### ISSUE THREAD

**Issue by jaiwonlee1** [mdryden/110yards#29]
Hi, great work with the site. I’m not usually one to correct points. But it’s our championship! Kyries Hebert had 7 defensive tackles and 1 fumble recovery against HAM according to cfl box score website. Wouldn’t this be 17 pts? Thanks!

**Comment by jaiwonlee1** [comment]
It shows as 14 pts. Thanks.

**Comment by mdryden** [comment]
It would be, yes.

It looks like he's not getting credit for the recovery.  It's likely that
the official scoring didn't record it.  If so, it should get a correction
when the week ends after the last game.

I'll double check when I'm at a computer though
