### ISSUE TITLE
League starting on Week two

### ISSUE THREAD

**Issue by KAI1984** [mdryden/110yards#8]
I started a league in the middle of week one and want to re-set the scores so the league begins on week 2. Is there a way to delete week one scores? Our league name is Thenewleague

**Comment by pudds** [comment]
I can probably do that for you, I'll take a look tomorrow.

**Comment by KAI1984** [comment]
I am not able to log into by account (kaiehorsfield@gmail.com). I tried to
reset my password and that did not work either.

**Comment by doh77** [comment]
I realized i do not know how to get you funds. Is there somewhere you are registered for this? Or can i send it from this site? ALso our league is at the link below.

https://110yards.ca/league/42

**Comment by mdryden** [comment]
This is done, sorry for the delay, I started a new job and life got hectic.

Please don't feel obligated to send me anything, but if you do want to, my paypal email is: pudds55(at)gmail.com (with an @ sign instead of (at) of course).

Glad you're enjoying the site.

**Comment by mdryden** [comment]
Yes, please email me your email address.

Mike

**Comment by KAI1984** [comment]
Kaiehorsfield@gmail.com
